export const REQUEST_BOOKINGS = 'REQUEST_BOOKINGS';
export const RECEIVE_BOOKINGS = 'RECEIVE_BOOKINGS';
export const REQUEST_SELLERS = 'REQUEST_SELLERS';
export const RECEIVE_SELLERS = 'RECEIVE_SELLERS';
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
