export const REQUEST_BOOKINGS = 'REQUEST_BOOKINGS';
export const RECEIVE_BOOKINGS = 'RECEIVE_BOOKINGS';
export const REQUEST_SELLERS = 'REQUEST_SELLERS';
export const RECEIVE_SELLERS = 'RECEIVE_SELLERS';
